openapi: 3.0.0

info:
  title: GetID API
  version: "1.5"
  x-logo:
    url: "./logo.svg"
    altText: GetID

  description: |
    # Overview

    The GetID API allows you to send applications for verification and receive the results.
    Verification results for applications created using our SDKs can also be obtained through the API.

    # Authentication

    The GetID API uses token-based authentication. 
    API tokens must be included in the header of all requests made to the API.

    <SecurityDefinitions />

tags:
  - name: "Application"
    x-displayName: "Applications"
    description: |
      "Application" is the basic concept used in this API.
      It is a set of data that have to be verified, is being verified or has already been verified.

      It may contain text data of the applicant's profile, image(s) of his/her identity document, selfie of the applicant, as well as additional files.
      Also, if the application was created using our SDK, it may contain artefacts confirm that the applicant passes the liveness check.
  - name: "Translation"
    x-displayName: "Translations"
  - name: "Token"
    x-displayName: "Tokens"
  - name: "One-time link"
    x-displayName: "One-time links"
  - name: "ApplicationToVerify"
    x-displayName: "Application to verify"
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/ApplicationToVerifyContainer" />
  - name: "VerificationResult"
    x-displayName: "Verification result"
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/VerificationResult" />
x-tagGroups:
  - name: Endpoints
    tags:
      - "Application"
      - "Token"
  - name: Models
    tags:
      - "ApplicationToVerify"
      - "VerificationResult"
  - name: SDK-related endpoints
    tags:
      - "Translation"
      - "One-time link"

paths:
  /api/v1/application:
    post:
      summary: "Create an application"
      security:
        - APIKeyAuth: []
        - APITokenAuth: []
      description: |
        Submits an application for verification.
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/ApplicationToVerifyContainer"
      responses:
        "200":
          description: OK.
          content:
            "application/json":
              schema:
                allOf:
                  - type: object
                    properties:
                      id:
                        $ref: "#/components/schemas/ApplicationID"
                    required: [id]
                  - $ref: "#/components/schemas/ResponseCode200"
        "400":
          description: Bad request.
          content:
            "application/json":
              schema:
                allOf:
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/ApplicationValidationError"
                  - $ref: "#/components/schemas/ResponseCode400"
        "401":
          $ref: "#/components/responses/Unauthorized"
      callbacks:
        onOrderedCallback:
          "custom predefined by client webhook url":
            post:
              parameters:
                - in: header
                  name: Cache-Control
                  description: instructions for caching
                  schema:
                    type: string
                    example: "no-cache"
                - in: header
                  name: Accept
                  schema:
                    type: string
                    example: "application/json"
                - in: header
                  name: Content-Type
                  description: type of content
                  schema:
                    type: string
                    example: "application/json"
                - in: header
                  name: X-Signature
                  description: The Response hashed with a timestamp and signed with a private key
                  schema:
                    type: string
                - in: header
                  name: X-Timestamp
                  description: Timestamp (moment of signing)
                  schema:
                    type: number
                    format: unix timestamp
              requestBody:
                content:
                  "application/json":
                    schema:
                      $ref: "#/components/schemas/VerificationResult"
              responses:
                "200":
                  description: OK.
      tags: ["Application"]

  /api/v1/application/{id}:
    get:
      summary: "Inspect an application"
      security:
        - APIKeyAuth: []
        - APITokenAuth: []
      description: |
        Retrieves a previously submitted application by providing its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: "#/components/schemas/ApplicationID"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                allOf:
                  - $ref: "#/components/schemas/VerificationResult"
                  - $ref: "#/components/schemas/ResponseCode200"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
      tags: ["Application"]
    delete:
      summary: "Delete an application"
      security:
        - APIKeyAuth: []
        - APITokenAuth: []
      description: |
        Deletes a previously submitted application by providing its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: "#/components/schemas/ApplicationID"
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
      tags: ["Application"]

  /api/v1/pdf/{id}:
    get:
      summary: "Get an application in PDF format"
      security:
        - APIKeyAuth: []
        - APITokenAuth: []
      description: |
        Retrieves a previously submitted application in PDF format.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: "#/components/schemas/ApplicationID"
      responses:
        "200":
          description: OK.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
      tags: ["Application"]

  /api/v1/applications-list:
    get:
      summary: "List applications"
      security:
        - APIKeyAuth: []
        - APITokenAuth: []
      description: |
        Lists the submitted applications.
      parameters:
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/endDate'
        - $ref: '#/components/parameters/statusFilter'
        - $ref: '#/components/parameters/countryFilter'
        - $ref: '#/components/parameters/docTypeFilter'
        - $ref: '#/components/parameters/platformFilter'
        - $ref: '#/components/parameters/authorFilter'
        - $ref: '#/components/parameters/flowFilter'
        - $ref: '#/components/parameters/pageLimit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/idsOnly'
      responses:
        "200":
          description: OK.
          content:
            "application/json":
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApplicationListResponse"
                  - $ref: "#/components/schemas/ResponseCode200"
        "401":
          $ref: "#/components/responses/Unauthorized"
      tags: ["Application"]

  /api/v1/tokenized-url:
    post:
      summary: "Create a one-time verification link"
      security:
        - APIKeyAuth: []
        - APITokenAuth: []
      description: |
        Creates a one-time verification link.

        An end user, by following the created link, will be able to submit an application for verification using our SDK.
      parameters:
        - in: query
          name: name
          description: |
            The name of the verification flow. 
            You can create, view, edit and delete verification flows in the Administrative Portal.
          schema:
            type: string
            example: getid-doc-selfie-liveness
          required: true
        - in: query
          name: externalId
          description: A unique identifier.
          schema:
            type: string
            example: dse31-sla05-wte93
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/SDKConfiguration"
      responses:
        "200":
          description: OK.
          content:
            'application/json':
              schema:
                properties:
                  url:
                    type: string
                    description: The verification link.
                required: [url]
        "401":
          $ref: "#/components/responses/Unauthorized"
      tags: ["One-time link"]

  /api/v1/translations:
    post:
      summary: "Create a translation dictionary"
      security:
        - APIKeyAuth: []
      description: |
        Creates a translation dictionary.
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Dictionaries"
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
      tags: ["Translation"]
    get:
      summary: "List translation dictionaries"
      description: |
        Returns all translation dictionaries.
      responses:
        "200":
          description: OK.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dictionaries"
        "401":
          $ref: "#/components/responses/Unauthorized"
      tags: ["Translation"]
  
  /api/v1/translations/{dictionary}/{locale}:
    delete:
      summary: "Delete a translation dictionary"
      security:
        - APIKeyAuth: []
      description: |
        Deletes a translation dictionary.
      parameters:
        - in: path
          name: dictionary
          required: true
          schema:
            type: string
        - in: path
          name: locale
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
      tags: ["Translation"]

  /api/v1/token:
    post:
      summary: "Create a token"
      security:
        - APIKeyAuth: []
      description: |
        Creates a token.
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/APITokenToCreate"
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
      tags: ["Token"]

  /api/v1/token/{token}:
    delete:
      summary: "Delete a token"
      security:
        - APIKeyAuth: []
      description: |
        Deletes a token.
      parameters:
        - in: path
          name: token
          description: The token to be deleted.
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
      tags: ["Token"]

components:

  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: |
        Your API key can be used as a token. 
        The API key can be found in the Settings section of the Administrative Portal.

        The API key provides access to all submitted applications, so keep it in safety. Never use the API key in the frontend side of your system.
        
    APITokenAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: |
        Tokens created using the `POST api/v1/token` method give access only to applications created using the very same token.
        
        Such tokens can be deleted using `DELETE api/v1/token/{token}` method, for example, if a token has been compromised or when staff members with access to a token leave your organisation.

        Note: tokens with `root` access level provide access to all submitted applications.

  parameters:
    startDate:
      name: startDate
      in: query
      schema:
        type: integer
    endDate:
      name: endDate
      in: query
      schema:
        type: integer
    statusFilter:
      name: statusFilter
      in: query
      schema:
        type: array
        items:
          type: string
          enum:
            - declined
            - approved
            - needs-review
            - error
            - pending
    countryFilter:
      name: countryFilter
      in: query
      schema:
        type: array
        items:
          type: string
          description: Alpha3 country code
    docTypeFilter:
      name: docTypeFilter
      in: query
      schema:
        type: array
        items:
          $ref: "#/components/schemas/DocumentType"
    platformFilter:
      name: platformFilter
      in: query
      schema:
        type: array
        items:
          type: string
          enum:
            - api
            - web
            - ios
            - android
    authorFilter:
      name: authorFilter
      in: query
      schema:
        type: array
        description: array of userNames, available option "No author" - returns applications without author
        items:
          type: string
    flowFilter:
      name: flowFilter
      in: query
      schema:
        type: array
        description: array of verification flows
        items:
          type: string
    pageLimit:
      name: pageLimit
      in: query
      schema:
        type: integer
    offset:
      name: offset
      in: query
      schema:
        type: integer
    idsOnly:
      name: idsOnly
      in: query
      schema:
        type: boolean

  responses:
    OK:
      description: OK.
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ResponseCode200"
    Unauthorized:
      description: Unauthorized access, invalid or missing authorization header.
      content:
        "application/json":
          schema:
            properties:
              responseCode:
                type: integer
                enum: [401]
              errorMessage:
                type: string
                example: "Wrong API key"
            required: [responseCode]
    NotFound:
      description: Resource not found.
      content:
        "application/json":
          schema:
            properties:
              responseCode:
                type: integer
                enum: [404]
            required: [responseCode]

  schemas:

    ApplicationToVerifyContainer:
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/ApplicationToVerifyMetadata"
        application:
          $ref: "#/components/schemas/ApplicationToVerify"
        verificationTypes:
          $ref: "#/components/schemas/VerificationsToPerform"
      required: [application]
      additionalProperties: false

    ApplicationToVerifyMetadata:
      type: object
      properties:
        externalId:
          type: string
          description: Use this field to set custom ID from your system
          example: ID-342
        labels:
          type: object
          description: Custom key-value labels (maximum 30)
          maxProperties: 30
          additionalProperties:
            type: string

    ApplicationToVerify:
      type: object
      description: The data to verify.
      properties:
        fields:
          allOf:
            - description: The profile data of the applicant.
            - $ref: "#/components/schemas/ProfileDataFields"
        documents:
          type: array
          description: The document to verify.
          items:
            $ref: "#/components/schemas/DocumentToVerify"
          minItems: 0
          maxItems: 1
        selfie:
          description: The applicant's selfie.
          properties:
            files:
              type: array
              items:
                $ref: "#/components/schemas/MediaFile"
              minItems: 0
              maxItems: 1
          required: [files]
          additionalProperties: false
      additionalProperties: false

    ProfileDataFields:
      type: array
      description: |
        The profile data of the applicant.
      items:
        $ref: "#/components/schemas/ProfileDataField"
      example:
        - category: First name
          content: John
          contentType: string
        - category: Last name
          content: Doe
          contentType: string
        - category: Gender
          content: male
          contentType: sex

    ProfileDataField:
      type: object
      properties:
        category:
          type: string
          description: |
            Kind of data.
            For example: First name, Last name, Date of birth, Gender
          example: First name
        content:
          type: string
          description: |
            The field value. It must be compliant with the category's format.
            The gender field can take only two values: male, female
            Dates must be in YYYY-MM-DD format
            Country fields must be in [alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements) format
            Other fields are plain strings
          example: John
        contentType:
          $ref: "#/components/schemas/ContentType"
      required: [category, content]
      additionalProperties: false

    DocumentToVerify:
      type: object
      properties:
        issuingCountry:
          $ref: "#/components/schemas/IssuingCountryCode"
        documentType:
          $ref: "#/components/schemas/DocumentType"
        files:
          description: Document photos or scans
          type: array
          items:
            $ref: "#/components/schemas/DocumentPageMediaFile"
          minItems: 1
          maxItems: 2
      required: [files]
      additionalProperties: false

    IssuingCountryCode:
      type: string
      description: |
        The code of the issuing country of the document. Format: ISO 3166-1
        ([alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)
        or [alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements))
      pattern: ^[a-zA-Z]{2,3}$
      example: JPN

    DocumentType:
      type: string
      description: A type of a document.
      enum:
        - passport
        - id-card
        - driving-licence
        - residence-permit
        - voter-card
        - tax-card
        - address-card
        - domestic-passport
        - unknown
      example: id-card

    DocumentPageKind:
      type: string
      description: kind of document page
      enum: [front, back, single-page]
      example: front

    DocumentPageMediaFile:
      type: object
      allOf:
        - type: object
          properties:
            kind:
              $ref: "#/components/schemas/DocumentPageKind"
          required: [kind]
        - $ref: "#/components/schemas/MediaFile"
      additionalProperties: false

    MediaFile:
      type: object
      properties:
        uri:
          description: |
            Data URI of the media
            All common image formats are acceptable.
          type: string
          format: media-data-uri
          example: data:image/png;base64,aGVsbG8=
      required: [uri]
      additionalProperties: false

    Watchlists:
      type: string
      description: check a user on PEPs
      enum: [watchlists]

    FaceMatching:
      type: string
      description: compare a photo on the document with a selfie
      enum: [face-matching]

    DataExtraction:
      type: string
      description: extract data from documents
      enum: [data-extraction]

    CrossChecking:
      type: string
      description: check the conformity between fields and extracted data
      enum: [cross-checking]

    Liveness:
      type: string
      description: liveness check
      enum: [liveness]

    VerificationsToPerform:
      type: array
      description: >
        List of requested verifications.
        If the list isn't provided, all verifications will be applied.
      items:
        $ref: "#/components/schemas/VerificationToPerform"
      example: ["watchlists", "face-matching", "data-extraction", "cross-checking"]

    VerificationToPerform:
      oneOf:
        - $ref: "#/components/schemas/Watchlists"
        - $ref: "#/components/schemas/FaceMatching"
        - $ref: "#/components/schemas/DataExtraction"
        - $ref: "#/components/schemas/CrossChecking"

    ApplicationListResponse:
      type: object
      properties:
        applicationsList:
          type: array
          items:
            $ref: "#/components/schemas/VerificationResult"
        applicationsListIds:
          type: array
          items:
            type: string
        applicationsListTotalItems:
          type: integer
      required: [applicationsListTotalItems]
      additionalProperties: false

    ApplicationID:
      type: string
      description: The ID of the application.
      format: object-id
      example: 5e62110968e3fb4d655756d1

    VerificationResult:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/ApplicationID"
        metadata:
          $ref: "#/components/schemas/Metadata"
        application:
          $ref: "#/components/schemas/Application"
        verificationTypes:
          $ref: "#/components/schemas/VerificationTypes"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        overallResult:
          $ref: "#/components/schemas/OverallResult"
        servicesResults:
          $ref: "#/components/schemas/ServiceResults"
        comment:
          $ref: "#/components/schemas/Comment"
      required:
        - id
        - metadata
        - application
        - processingState

    Metadata:
      type: object
      description: |
        The meta information about the input data source.
        This field can be used to add custom meta information.
        It will also be added to the response as-is.
      properties:
        externalId:
          type: string
          description: Use this field to set custom ID from your system
          example: ID-342
        platform:
          type: string
          description: The platform type an application is sent from
          example:
            - android
            - ios
            - web
        clientName:
          type: string
          description: The name of a client who sent a request
          example: my-api-client
        clientVersion:
          type: string
          description: The version of a client who sent a request
          example: 1.0.0
        acVersion:
          type: string
          description: The version of an acceptor client who received the request
          example: 1.0.0
        ipAddress:
          type: string
          description: The IP address a request was sent from
          example: 8.8.8.8
        country:
          type: string
          description: A country detected from IP address
          example: EST
        city:
          type: string
          description: A city detected from IP address
          example: Tallinn
        userAgent:
          type: string
          description: User agent data retrieved from the user's client who sent an app from SDK
          example: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
        author:
          type: string
          description: A username or email of an author of the request
          example: admin
        disableCs:
          type: boolean
          description: It allows to disable the customer support check
          example: true
        labels:
          type: object
          description: Custom key-value labels (maximum 30)
          maxProperties: 30
          additionalProperties:
            type: string
        createdBy:
          type: string
          enum: [web-desktop, web-mobile, android, ios]
          description: Represent the source of starting the verification
        createdAt:
          description: The time when the application was created.
          type: string
          format: date-time
          example: "2020-03-17T20:28:37.061Z"
      example:
        externalId: ID-2345
        platform: android
        clientName: my-api-client
        clientVersion: 1.0.0
        labels:
          my-custom-meta-name-1: custom-value-1
          my-custom-meta-name-2: custom-value-2

    Application:
      type: object
      properties:
        fields:
          $ref: '#/components/schemas/ProfileDataFields'
        documents:
          type: array
          items:
            $ref: "#/components/schemas/ResultDocument"
        selfie:
          properties:
            files:
              type: array
              items:
                $ref: "#/components/schemas/ResultFacesMedia"
          required: [files]
          additionalProperties: false
      additionalProperties: false

    ResultDocument:
      type: object
      properties:
        issuingCountry:
          $ref: "#/components/schemas/IssuingCountryCode"
        documentType:
          $ref: "#/components/schemas/DocumentType"
        files:
          description: Temporary links to the document photos or scans
          type: array
          items:
            $ref: "#/components/schemas/ResultDocumentMedia"
      required: [files]
      additionalProperties: false

    ResultFacesMedia:
      type: object
      properties:
        id:
          type: string
          description: file id (filled automatically when missing)
        uri:
          $ref: "#/components/schemas/MediaURI"
        mediaType:
          type: string
          example: image/jpeg
        kind:
          type: string
          enum: [selfie, liveness-video, liveness-full-face]
          example: selfie
      required: [uri]
      additionalProperties: false

    MediaURI:
      type: string
      description: A temporary link to a media file.
      format: uri
      example: https://some.site/image.jpeg?t=123

    ResultDocumentMedia:
      type: object
      properties:
        id:
          type: string
          description: The file id (filled automatically when missing)
        kind:
          $ref: "#/components/schemas/DocumentPageKind"
        uri:
          $ref: "#/components/schemas/MediaURI"
        mediaType:
          type: string
          example: image/jpeg
      required: [id, uri, kind]
      additionalProperties: false

    VerificationTypes:
      type: array
      description: The list of checks performed.
      items:
        oneOf:
          - $ref: "#/components/schemas/Watchlists"
          - $ref: "#/components/schemas/FaceMatching"
          - $ref: "#/components/schemas/DataExtraction"
          - $ref: "#/components/schemas/CrossChecking"
          - $ref: "#/components/schemas/Liveness"
      example: ["face-matching", "data-extraction", "liveness"]

    ProcessingState:
      type: string
      enum:
        - done
        - processing
      description: |
        Application processing state:
          * `done` - the processing is finished
          * `processing` - the application is being processed

    OverallResult:
      type: object
      description: Summary verification result (ommitted if the state is `processing`)
      properties:
        status:
          allOf:
            - description: The worst result from all services
            - $ref: "#/components/schemas/VerificationStatus"
        comments:
          type: array
          description: An array of results from all services (You can find full results in the servicesResults section)
          items:
            type: object
            properties:
              service:
                description: A service name
                type: string
              status:
                $ref: "#/components/schemas/VerificationStatus"
              comment:
                description: A short comment about the result
                type: string
            required:
              - service
              - status
          example:
            - service: face-matching
              status: approved
              comment: faces are similar
            - service: watchlists
              status: declined
              comment: found 2 reports against the person
            - service: data-extraction
              status: approved
              comment: data was extracted
        concerns:
          $ref: "#/components/schemas/Concerns"
        validationDate:
          $ref: "#/components/schemas/ValidationDate"
      additionalProperties: false
      required:
        - status
        - comments
        - validationDate

    Concerns:
      type: array
      items:
        type: object
        properties:
          message:
            type: string
          service:
            type: string
          status:
            type: string
      example:
        - service: face-matching
          status: declined
          comment: The photo is not a selfie.
        - service: crosschecking
          status: needs-review
          comment: The last name extracted from the document doesn't match the last name from the profile data.

    ValidationDate:
      type: string
      description: The date and time of completion of the validation.
      format: date-time
      example: "2020-03-17T20:28:37.061Z"

    SummaryResult:
      type: object
      description: The summary verification result (ommitted if the state is `processing`)
      properties:
        status:
          description: The worst result from all services
          $ref: "#/components/schemas/VerificationStatus"
        document:
          $ref: "#/components/schemas/ResultDocument"
        concerns:
          $ref: "#/components/schemas/Concerns"
        validationDate:
          $ref: "#/components/schemas/ValidationDate"
      additionalProperties: false
      required:
        - status
        - validationDate

    VerificationStatus:
      type: string
      description: |
        The result of verification:
        * `approved` - no problems are found
        * `declined` - an application is declined due to any facts defined as critical in Settings
        * `needs-review` - some facts are defined as considered in Settings
        * `error` - an error has occurred (wrong or missing input data; service error)
      enum:
        - declined
        - approved
        - needs-review
        - error
    
    BreakdownStatus:
      type: string
      description: |
        Breakdown status:
        * `approved` - the check is successful
        * `declined` - the check has failed
        * `needs-review` - the check has failed, manual review is needed
        * `disabled` - the check is disabled
      enum:
        - declined
        - approved
        - needs-review
        - disabled
 
    ServiceResults:
      type: object
      properties:
        faceMatching:
          $ref: "#/components/schemas/FaceMatchingServiceResult"
        livenessCheck:
          $ref: "#/components/schemas/LivenessCheckServiceResult"
        dataExtraction:
          $ref: "#/components/schemas/DataExtractionServiceResult"
        crossChecking:
          $ref: "#/components/schemas/CrossCheckingServiceResult"
        watchlists:
          $ref: "#/components/schemas/WatchlistsServiceResult"
        docCheck:
          $ref: "#/components/schemas/DocCheckServiceResult"
        profileCheck:
          $ref: "#/components/schemas/ProfileCheckServiceResult"
      additionalProperties: false

    FaceMatchingServiceResult:
      type: object
      description: The Face-matching service compares a photo on the document with a selfie
      properties:
        comment:
          description: A short comment about the result
          type: string
          example: Faces are not similar
        verifier:
          description: Name of the verifier
          type: string
          example: Facemelter
        status:
          $ref: "#/components/schemas/VerificationStatus"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        results:
          $ref: "#/components/schemas/FaceMatchingResult"
        settings:
          type: object
          description: |
            Settings determining a result status.
            If both threshold are equal, the result status can only be `declined` or `approved`
          properties:
            declineThreshold:
              description: A threshold between `declined` and `needs-review` statuses
              type: number
              example: 0.4
            needsReviewThreshold:
              description: A threshold between `needs-review` and `approved` statuses
              type: number
              example: 0.6
      required:
        - status
      additionalProperties: false

    FaceMatchingResult:
      type: array
      description: The Face-matching service result
      items:
        properties:
          files:
            description: File ids that were involved in checking
            type: array
            minItems: 0
            maxItems: 3
            uniqueItems: true
            items:
              type: string
            example: [face-abc1, document-photo-qwe7]
          selfieQuality:
            $ref: "#/components/schemas/CheckList"
          score:
            description: The faces similarity score
            type: number
            example: 0.3
        required:
          - score
          - files
        additionalProperties: false

    LivenessCheckServiceResult:
      type: object
      properties:
        comment:
          type: string
        verifier:
          type: string
        status:
          $ref: "#/components/schemas/VerificationStatus"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        livenessCheck:
          $ref: "#/components/schemas/CheckList"
      required:
        - status
      additionalProperties: false
   
    DataExtractionServiceResult:
      type: object
      properties:
        comment:
          type: string
        verifier:
          type: string
        status:
          $ref: "#/components/schemas/VerificationStatus"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        extracted:
          $ref: "#/components/schemas/Extracted"
      required:
        - status
      additionalProperties: false
      example:
        comment: Data was extracted
        verifier: DeerPlugin
        status: approved
        extracted:
          - documentId: passport-1
            ocr:
              - contentType: string
                category: First name
                content: Joe
              - contentType: string
                category: First name
                content: Джо
                locale: ru_RU
              - contentType: string
                category: Last name
                content: Black
            mrz:
              - contentType: string
                category: First name
                content: James
              - contentType: string
                category: Last name
                content: Black
          - documentId: driving-licence-1
            ocr:
              - contentType: string
                category: First name
                content: Joe
              - contentType: string
                category: Address
                content: May street

    DataExtractionResult:
      type: object
      properties:
        contentType:
          $ref: "#/components/schemas/ContentType"
        category:
          type: string
          description: The extracted field name
        content:
          type: string
          description: The extracted field value
        locale:
          type: string
          description: The extracted value locale
          example: en_UK
        extractedFormat:
          type: string
          description: The extracted date format, applicable if a date is presented in non-default format YYYY-MM-DD
          example: YYYY-MM
        valid:
          type: boolean
      required:
        - contentType
        - category
        - content
      additionalProperties: false

    DocCheckServiceResult:
      type: object
      properties:
        comment:
          type: string
        verifier:
          type: string
        status:
          $ref: "#/components/schemas/VerificationStatus"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        documentDataChecking:
          type: array
          items:
            $ref: "#/components/schemas/DocumentDataChecking"
        documentPhotoQuality:
          $ref: "#/components/schemas/CheckList"
        dataExtractionConsistency:
          $ref: "#/components/schemas/CheckList"

    Extracted:
      type: array
      items:
        type: object
        properties:
          documentId:
            type: string
            description: The document ID from which data was extracted
          ocr:
            type: array
            items:
              $ref: "#/components/schemas/DataExtractionResult"
          mrz:
            type: array
            items:
              $ref: "#/components/schemas/DataExtractionResult"
          images:
            type: array
            items:
              properties:
                kind:
                  type: string
                  example: portrait
                uri:
                  $ref: "#/components/schemas/MediaURI"
              additionalProperties: false
              required:
                - kind
                - uri
        additionalProperties: false

    ProfileCheckServiceResult:
      type: object
      properties:
        comment:
          type: string
        verifier:
          type: string
        status:
          $ref: "#/components/schemas/VerificationStatus"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        formCompare:
          $ref: "#/components/schemas/CheckList"
        matchLocation:
          $ref: "#/components/schemas/CheckList"
        fieldChecking:
          type: array
          items:
            $ref: "#/components/schemas/FieldChecking"

    CrossCheckingServiceResult:
      type: object
      properties:
        comment:
          type: string
        verifier:
          type: string
        status:
          $ref: "#/components/schemas/VerificationStatus"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        fieldChecking:
          type: array
          items:
            $ref: "#/components/schemas/FieldChecking"
          description: |
            Contains a list of checked fields
            If the value corresponding to the field wasn't extracted, such case will also be added to the list
          example:
            - category: First name
              field: John
              extracted: Joanna
              equal: false
              documentId: passport-1
            - category: Last name
              field: Doe
              extracted: ""
              equal: false
              documentId: passport-1
            - category: Date of birth
              field: "1999-09-31"
              extracted: "1999-09-31"
              equal: true
              documentId: passport-1
            - category: Address
              field: May street
              extracted: April street
              equal: false
              documentId: driving-licence-1
        documentDataChecking:
          type: array
          items:
            $ref: "#/components/schemas/DocumentDataChecking"
        documentPhotoQuality:
          $ref: "#/components/schemas/CheckList"
        originalDocumentPresence:
          $ref: "#/components/schemas/CheckList"
        documentQuality:
          $ref: "#/components/schemas/CheckList"
        fraudAssesment:
          $ref: "#/components/schemas/CheckList"
        formCompare:
          $ref: "#/components/schemas/CheckList"
        matchLocation:
          $ref: "#/components/schemas/CheckList"
        documentCompare:
          $ref: "#/components/schemas/CheckList"
        dataExtractionConsistency:
          $ref: "#/components/schemas/CheckList"
      required:
        - status
      additionalProperties: false

    FieldChecking:
      type: object
      properties:
        category:
          type: string
          example: First name
        field:
          type: string
          example: John
        extracted:
          type: string
          example: Joanna
        equal:
          type: boolean
        status:
          allOf:
            - $ref: "#/components/schemas/BreakdownStatus"
            - description: The data check status

        documentId:
          type: string
          description: The document ID from which extracted data is compared
      required:
        - category
        - field
        - extracted
        - equal
      additionalProperties: false

    DocumentDataChecking:
      type: object
      properties:
        category:
          type: string
          example: First name
        mrz:
          type: string
        ocr:
          type: string
        equal:
          type: boolean
          nullable: true
          description: Null means that the check between fields on the document was not performed
        valid:
          type: boolean
          description: The document field validation result (false means that value is incorrect)
        status:
          allOf:
            - $ref: "#/components/schemas/BreakdownStatus"
            - description: The check data status
        message:
          type: string
        documentId:
          type: string
          description: The document ID from which extracted data is compared
        conflicts:
          description: A list of conflicts
          type: array
          items:
            type: string
      required:
        - category
        - equal
      additionalProperties: false

    WatchlistsServiceResult:
      type: object
      properties:
        comment:
          type: string
        verifier:
          type: string
        status:
          $ref: "#/components/schemas/VerificationStatus"
        processingState:
          $ref: "#/components/schemas/ProcessingState"
        sentFields:
          type: array
          items:
            type: string
          description: The list of profile data fields that have been sent to the watchlist service.
          example: ["First name", "Last name", "Date of birth"]
        summary:
          $ref: "#/components/schemas/CheckList"
        records:
          type: array
          items:
            $ref: "#/components/schemas/WatchlistsRecord"
      required:
        - status
      additionalProperties: false
    
    WatchlistsRecord:
      type: object
      description: Watchlists' record can be of any data structure
    
    ContentType:
      type: string
      description: A type of a profile data field content. Deprecated.
      enum: [string, number, sex, date, country, boolean]

    Comment:
      type: object
      description: A user's comment.
      properties:
        text:
          type: string
          description: The text of the comment.
          example: "Everything's OK"
        author:
          type: string
          description: The login of the comment's author.
          example: "admin"
        createdAt:
          type: string
          description: The date and time of the comment's creation.
          format: date-time
          example: "2020-03-17T20:28:37.061Z"
  
    CheckList:
      type: object
      properties:
        group:
          type: string
        description:
          type: string
        considers:
          type: array
          items:
            properties:
              name:
                type: string
              description:
                type: string
              type:
                type: string
              status:
                type: string
            additionalProperties: false
            required:
              - name
              - description
      additionalProperties: false
      required:
        - group
        - considers
    
    ApplicationValidationError:
      type: object
      properties:
        keyword:
          type: string
          description: |
            Describes the type of validation that wasn't passed. Examples: required, type, format, pattern.
          example: pattern
        dataPath:
          type: string
          description: The path to the invalid data.
          example: .application.documents[0].issuingCountry
        schemaPath:
          type: string
          description: The reference to the schema.
          example: "#/components/schemas/ApplicationToVerify/properties/documents/items/properties/issuingCountry/pattern"
        params:
          type: object
          example:
            pattern: ^[a-zA-Z]{2,3}$
        message:
          type: string
          description: A human-readable description of the error.
          example: it should match the pattern "^[a-zA-Z]{2,3}$"
      additionalProperties: false
    
    SDKConfiguration:
      type: object
      properties:
        locale:
          type: string
          description: Predefine locale
          example: de
        profile:
          type: object
          description: Pre-fill Form fields according to the SDK configuration
        redirects:
          type: object
          description: Specify an URL to redirect
          properties:
            onComplete:
              type: string
              description: Redirect after Complete event
              example: https://google.com
            onFail:
              type: string
              description: Redirect after Fail event
              example: https://google.com
    
    Dictionaries:
      type: array
      items:
        properties:
          label:
            type: string
            description: It is the string that will be viewed in the translation list
          dictionary:
            type: string
            description: Name of a custom dictionary (You should use this name in SDK config)
          locale:
            type: string
            description: locale
          default:
            type: boolean
            description: Use this translation by default
          items:
            properties:
              dictionaries:
                description: Key - value pairs for translations
                type: object
            additionalProperties: false
        required:
          - label
          - dictionary
          - locale
          - items

    APITokenToCreate:
      type: object
      properties:
        ttl:
          type: integer
          description: Time to live for the API token in seconds. The default value is 86400 (24 hours).
          example: 86400
        accessLevel:
          enum:
            - root
          type: string
          description: A token created with `root` access level can be used to retrieve any submitted application.
      additionalProperties: false

    ResponseCode200:
      type: object
      properties:
        responseCode:
          type: integer
          enum: [200]
      required: [responseCode]

    ResponseCode400:
      type: object
      properties:
        responseCode:
          type: integer
          enum: [400]
      required: [responseCode]
